dataset: "realworld"
meas_result: True
with_variance: False
use_relative_pose: True
pseduo_discrete: True
save_map: True
result_split: "val"
grid_params:
  grid_size: [ 200.0, 200.0, 80.0,]
  min_bound: [-5.0, -5.0, -2.0, ]
  max_bound: [ 5.0, 5.0, 2.0,]
filter_size: 3
ell: 0.5